# Site settings
title: Jasper Bae
description: My Professional Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jasper Bae
user_description: I'm an entrepreneurial developer working to develop applications that make the world we live in more convenient and happier. I love to brainstorm reusable applications that portray data in a different light. My ultimate vision is to design and program applications that will make the world a better place – a world interconnected with technology. Visit my blog at <a href="https://breakpointmoments.com" target="_blank">Breakpoint Moments</a>
user_title: Software Developer
email: jasper.bae@rutgers.edu
# twitter_username: lorem_ipsum
github_username: nemferno
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
    id: ''

exclude: ['package.json', 'src', 'node_modules']
