# From https://javascript.plainenglish.io/deploy-your-next-js-app-on-github-pages-using-the-github-action-525271137409
# Builds and Deploys to Github gh-pages
name: Build and Deploy
on: [push]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
              with:
                  persist-credentials: false

            - name: Cache  💾
              uses: actions/cache@v2
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

            - name: Make .env.local file
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_AWS_API_KEY: ${{ secrets.AWS_API_KEY }}
                  envkey_MONGODB_DB: ${{ secrets.MONGODB_DB }}
                  envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
                  file_name: .env.local

            - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              uses: actions/setup-node@v1
            - run: npm install
            - run: npm run build
            - run: npm run export
              env:
                  CI: true
                  AWS_API_KEY: ${{ secrets.AWS_API_KEY }}
                  MONGODB_DB: ${{ secrets.MONGODB_DB }}
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
            - run: touch out/.nojekyll

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: out # The folder the action should deploy.
                  CLEAN: true # Automatically remove deleted files from the deploy branch
